[program:sistema-erp-mobile]
process_name=%(program_name)s
command=/usr/bin/node /var/www/sistema-erp/frontends/mobile/scripts/run-next.mjs start
directory=/var/www/sistema-erp/frontends/mobile
environment=PORT="3001",NODE_ENV="production"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/sistema-erp/frontends/mobile/logs/mobile.log
stopwaitsecs=10
