[program:sistema-erp-mobile]
process_name=%(program_name)s
command=/usr/bin/node /var/www/sistema-erp-mobile/current/node_modules/next/dist/bin/next start -p 3100 -H 127.0.0.1
directory=/var/www/sistema-erp-mobile/current
environment=NODE_ENV="production",HOME="/var/cache/sistema-erp/mobile"
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=5
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true
user=www-data
umask=0027
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/sistema-erp-mobile/mobile.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=15
